install:
    - ps: |
        # Here we nstall platyPS to the worker machine form the gallery
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module platyPS -Force
        Import-Module platyPS

build_script:
    - ps: |
        New-ExternalHelp -OutputPath en-US -Path ./docs -Force

test_script:
    - ps: |
        $OrgHelp = (Get-FileHash .\docs\*.md)
        Import-Module .\Greet.psm1 -Force
        Update-MarkdownHelp -Path ./docs
        $RecalcHelp = (Get-FileHash .\docs\*.md)
        if (Compare-Object $OrgHelp.Hash $RecalcHelp.Hash) {throw 'CHANGE DETECTED'}
        # TODO: load the Greet module and write a script
        # that will throw if docs are not up-to-date with the code.
        # In other words, if Update-MarkdownHelp changes the markdown.
